"""Initial migration

Revision ID: 01e626f8c63d
Revises: 
Create Date: 2025-10-03 17:30:58.251961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e626f8c63d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create trade_logs table
    op.create_table('trade_logs',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('order_id', sa.String(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('side', sa.String(), nullable=False),
        sa.Column('qty', sa.Float(), nullable=False),
        sa.Column('entry_price', sa.Float(), nullable=False),
        sa.Column('stop_price', sa.Float()),
        sa.Column('target_price', sa.Float()),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('(CURRENT_TIMESTAMP)')),
        sa.Column('entered_at', sa.DateTime()),
        sa.Column('exited_at', sa.DateTime()),
        sa.Column('exit_price', sa.Float()),
        sa.Column('pnl_usd', sa.Float()),
        sa.Column('r_multiple', sa.Float()),
        sa.Column('outcome', sa.String()),
        sa.Column('features', sa.JSON()),
        sa.Column('notes', sa.String()),
        sa.Column('model_score', sa.Float()),
        sa.Column('model_version', sa.String())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_logs')
    # ### end Alembic commands ###
