"""Add submitted_at column to trade_logs

Revision ID: 3b77eaf7a0c4
Revises: 01e626f8c63d
Create Date: 2025-10-04 21:27:59.730660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b77eaf7a0c4'
down_revision: Union[str, Sequence[str], None] = '01e626f8c63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_logs', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_logs', 'submitted_at')
    # ### end Alembic commands ###
