# AI Trading Agent Configuration

# Application settings
app:
  name: "AI Trading Agent"
  version: "0.1.0"
  debug: false
  timezone: "America/Phoenix"

# API configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  reload: true

# Database configuration
database:
  url: "sqlite:///./trading_agent.db"
  echo: false
  pool_size: 5
  max_overflow: 10

# Logging configuration
logging:
  level: "INFO"
  format: "json"
  file: null
  rotation: "daily"
  retention: 30

# Trading configuration
trading:
  default_broker: "paper"
  initial_capital: 100000.0
  commission_rate: 0.01

# Guardrails configuration
guardrails:
  max_trades_per_day: 5
  daily_loss_cap_usd: 300.0
  max_contracts: 10
  max_position_size_usd: 50000.0
  max_daily_volume_usd: 100000.0
  session_windows:
    - "06:30-08:00"
    - "08:30-10:00"

# Risk management
risk:
  check_interval: 1
  violation_cooldown: 300
  auto_halt_on_critical: true

# CORS configuration
cors:
  origins: ["*"]
  credentials: true
  methods: ["*"]
  headers: ["*"]

# MLflow configuration
mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "ai-trading-agent"
  artifact_root: "./mlruns"

# Monitoring
monitoring:
  enable_metrics: true
  metrics_port: 9090
  health_check_interval: 30
